name: pooler_flutter
description: Unofficial Pooler Flutter SDK
version: 1.0.0


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.10.0'

dependencies:
  connectivity_plus: ^5.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^3.0.1
